### ISSUE TITLE
Crash when resizing Calculator experiment

### ISSUE THREAD

**Issue by kaeawc** [androidx/constraintlayout#105]
Stack trace:
```2021-01-17 12:27:43.401 25980-25980/androidx.constraintlayout.experiments.calculator E/AndroidRuntime: FATAL EXCEPTION: main
    Process: androidx.constraintlayout.experiments.calculator, PID: 25980
    java.lang.RuntimeException: Unable to start activity ComponentInfo{androidx.constraintlayout.experiments.calculator/android.support.constraint.calc.MainActivity}: java.lang.NumberFormatException: For input string: "Hi Jamila - the app just notified me that you're done"
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5451)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5357)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NumberFormatException: For input string: "Hi Jamila - the app just notified me that you're done"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at java.lang.Double.valueOf(Double.java:502)
        at android.support.constraint.calc.CalcEngine.deserializeString(CalcEngine.java:186)
        at android.support.constraint.calc.CalcEngine.deserializeString(CalcEngine.java:178)
        at android.support.constraint.calc.MainActivity.regester_for_clipboard(MainActivity.java:310)
        at android.support.constraint.calc.MainActivity.onCreate(MainActivity.java:98)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5451) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5357) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-01-17 12:27:51.652 26271-26271/androidx.constraintlayout.experiments.calculator E/AndroidRuntime: FATAL EXCEPTION: main
    Process: androidx.constraintlayout.experiments.calculator, PID: 26271
    java.lang.RuntimeException: Unable to start activity ComponentInfo{androidx.constraintlayout.experiments.calculator/android.support.constraint.calc.MainActivity}: java.lang.NumberFormatException: For input string: "Hi Jamila - the app just notified me that you're done"
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5451)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5357)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NumberFormatException: For input string: "Hi Jamila - the app just notified me that you're done"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at java.lang.Double.valueOf(Double.java:502)
        at android.support.constraint.calc.CalcEngine.deserializeString(CalcEngine.java:186)
        at android.support.constraint.calc.CalcEngine.deserializeString(CalcEngine.java:178)
        at android.support.constraint.calc.MainActivity.regester_for_clipboard(MainActivity.java:310)
        at android.support.constraint.calc.MainActivity.onCreate(MainActivity.java:98)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5451) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5357) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by jafu888** [comment]
It is a cut paste buffer issue.  It needs to be wrapped in try catch();
Will deal with it in my next update.

**Comment by kaeawc** [comment]
The weird thing is I have no idea how I ever copied that text into my clipboard 😅
