### ISSUE TITLE
androidx.constraintlayout.motion.widget.MotionScene.mCurrentTransition' on a null object reference

### ISSUE THREAD

**Issue by Crone163** [androidx/constraintlayout#12]
On version 2.0.1 working is good.

On 2.0.2 crash log:

`2020-10-12 16:25:10.202 24740-24740/com.crone.skineditorforminecraftpe E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.crone.skineditorforminecraftpe, PID: 24740
    java.lang.NullPointerException: Attempt to read from field 'androidx.constraintlayout.motion.widget.MotionScene$Transition androidx.constraintlayout.motion.widget.MotionScene.mCurrentTransition' on a null object reference
        at androidx.constraintlayout.motion.widget.MotionLayout.onAttachedToWindow(MotionLayout.java:3486)
        at android.view.View.dispatchAttachedToWindow(View.java:21304)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2571)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:732)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
`

**Comment by MGaetan89** [comment]
This seems to be fixed in 2.0.3.
Can you confirm @Crone163?

**Comment by kaeawc** [comment]
Can confirm this is no longer possible as there is a null check on `mScene` here https://github.com/androidx/constraintlayout/commit/b78ac50cd5e1ee228ab4ba0d25c12669fc78f5df
