### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by himamis** [androidx/constraintlayout#368]
The following piece of Kotlin code produces an NPE.
```
val layout = MotionLayout(context)
val scene = MotionScene(layout )
layout .setScene(scene)
```
The exception:
```     Caused by: java.lang.NullPointerException: Attempt to read from field 'int androidx.constraintlayout.widget.ConstraintSet.mRotate' on a null object reference
        at androidx.constraintlayout.motion.widget.MotionLayout$Model.measure(MotionLayout.java:2763)
        at androidx.constraintlayout.motion.widget.MotionLayout$Model.reEvaluateState(MotionLayout.java:2716)
        at androidx.constraintlayout.motion.widget.MotionLayout.rebuildScene(MotionLayout.java:4586)
        at androidx.constraintlayout.motion.widget.MotionLayout.setScene(MotionLayout.java:3883)
```

**Comment by jafu888** [comment]
Merged your fix. Thanks!
