### ISSUE TITLE
NPE flow Android 12 Samsung

### ISSUE THREAD

**Issue by M66B** [androidx/constraintlayout#430]
I have seen a few crash logs like this being reported (Bugsnag), unfortunately I don't have anymore details, except that this is happening on Android 12 on Samsung devices:
```
10-26 08:02:25.996 11903 11903 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.constraintlayout.core.widgets.ConstraintWidget.getVisibility()' on a null object reference
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.Flow$WidgetsList.createConstraints(SourceFile:8)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.Flow.addToSolver(SourceFile:7)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.addChildrenToSolver(SourceFile:26)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(SourceFile:48)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(SourceFile:10)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(SourceFile:34)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(SourceFile:3)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(SourceFile:16)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:15)
10-26 08:02:25.997 11903 11903 W System.err: 	at android.view.View.measure(View.java:27110)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(SourceFile:62)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(SourceFile:47)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.Direct.horizontalSolvingPass(SourceFile:5)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveHorizontalMatchConstraint(SourceFile:15)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.Direct.horizontalSolvingPass(SourceFile:24)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.Direct.solvingPass(SourceFile:33)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(SourceFile:11)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(SourceFile:10)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(SourceFile:34)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(SourceFile:3)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(SourceFile:16)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:15)
10-26 08:02:25.997 11903 11903 W System.err: 	at android.view.View.measure(View.java:27110)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(SourceFile:62)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(SourceFile:47)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.Direct.horizontalSolvingPass(SourceFile:5)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveHorizontalMatchConstraint(SourceFile:15)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.Direct.horizontalSolvingPass(SourceFile:24)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.Direct.solvingPass(SourceFile:33)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(SourceFile:11)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(SourceFile:10)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(SourceFile:34)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(SourceFile:3)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(SourceFile:16)
10-26 08:02:25.997 11903 11903 W System.err: 	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:15)
10-26 08:02:25.997 11903 11903 W System.err: 	at android.view.View.measure(View.java:27110)
10-26 08:02:25.997 11903 11903 W System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.cardview.widget.CardView.onMeasure(SourceFile:11)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.measure(View.java:27110)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.measure(View.java:27110)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(SourceFile:14)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:11)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:9)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:65)
10-26 08:02:25.999 11903 11903 W System.err: 	at eu.faircode.email.FragmentMessages$7.onLayoutChildren(SourceFile:1)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:12)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:15)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
10-26 08:02:25.999 11903 11903 W System.err: 	at eu.faircode.email.FixedRecyclerView.onLayout(SourceFile:1)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.layout(View.java:24442)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(SourceFile:12)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.layout(View.java:24442)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SourceFile:11)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.layout(View.java:24442)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(SourceFile:18)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(SourceFile:7)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:8)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.layout(View.java:24442)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.layout(View.java:24442)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(SourceFile:10)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.layout(View.java:24442)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.layout(View.java:24442)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
10-26 08:02:25.999 11903 11903 W System.err: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(SourceFile:11)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.layout(View.java:24442)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.layout(View.java:24442)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.layout(View.java:24442)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-26 08:02:25.999 11903 11903 W System.err: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1309)
10-26 08:02:25.999 11903 11903 W System.err: 	at android.view.View.layout(View.java:24442)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4492)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3914)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2820)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10305)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1063)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:780)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1048)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.os.Looper.loop(Looper.java:313)
10-26 08:02:26.000 11903 11903 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8582)
10-26 08:02:26.000 11903 11903 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-26 08:02:26.000 11903 11903 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
10-26 08:02:26.000 11903 11903 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

**Comment by M66B** [comment]
This appears to happen on Android 11 / Samsung too.

**Comment by jafu888** [comment]
We will add code to prevent the exception but I suspect you have another issue.
Could you provide more details!
I see a RecyclerView. Is this a ConstraintLayout inside of one?
Are you adding / removing views programmatically ?

**Comment by M66B** [comment]
Thanks for the response @jafu888

I can't provider much more details, except that it seems to happen on Samsung devices with Android 11 and 12 only.

It is about a ConstraintLayout inside a RecyclerView.

Some views are added/removed programmatically. If this is the problem, is there a way to prevent this issue?

**Comment by M66B** [comment]
Possibly relevant code:

https://github.com/M66B/FairEmail/blob/master/app/src/main/java/eu/faircode/email/AdapterMessage.java#L1587

https://github.com/M66B/FairEmail/blob/master/app/src/main/java/eu/faircode/email/AdapterMessage.java#L2871
